### ISSUE TITLE
Longer order book

### ISSUE THREAD

**Issue by jpspfaria** [BitcoinExchangeFH/BitcoinExchangeFH#37]
Hi @gavincyi, 

You are developing an awesome system, great work!
I am looking forward to put your code to run 24/7 on some of my servers.

How can i to get a longer order book? I saw that some API can provide 100 records depth.

Is the actual orderbook table model good for this size of orderbook?

Thanks for the help 👍

**Comment by gavincyi** [comment]
Happy that you like my project :)

I think it can be put as an enhancement. The impact is on the performance as some exchanges provide RESTful API and long depth query requires a longer time to return due to the network bandwidth. However it is up to the user to weight between information and performance.

**Comment by jpspfaria** [comment]
Thanks for the fast reply.
Everything is working just fine on the new version!

Great work! Thanks a lot for your contribution.
On the next bitcoin meetup here in São Paulo/Brazil i will show your framework and i let you know the comments!

**Comment by gavincyi** [comment]
Definitely. Again thanks for your suggestion and will put the feature into the application! :)

**Comment by kfeeeeee** [comment]
Hi, just to make sure: this features is not implemented yet, is it (as @jpspfaria comment might imply)?

**Comment by gavincyi** [comment]
Yes correct it has not been implemented yet.

**Comment by gavincyi** [comment]
Enhanced in 2019.1.1
